export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life",
    price: 299.99,
    discount_percent: 15,
    image_url: "/images/product/fish-wood.jpg",
    stock: 45,
    is_new: true,
    is_popular: false,
  },
  {
    id: "2",
    name: "Ultra 4K Webcam",
    description: "Crystal clear 4K video quality with auto-focus and built-in microphone",
    price: 149.99,
    discount_percent: 0,
    image_url: "/images/product/salib.jpg",
    stock: 32,
    is_new: false,
    is_popular: true,
  },
  {
    id: "3",
    name: "Smart Watch Pro",
    description: "Advanced fitness tracking, heart rate monitor, and 14-day battery life",
    price: 399.99,
    discount_percent: 20,
    image_url: "/images/product/yesus.jpg",
    stock: 28,
    is_new: true,
    is_popular: true,
  },
  {
    id: "4",
    name: "USB-C Hub Adapter",
    description: "All-in-one hub with multiple ports for seamless connectivity",
    price: 79.99,
    discount_percent: 10,
    image_url: "/images/product/eci.jpg",
    stock: 120,
    is_new: false,
    is_popular: false,
  },
  {
    id: "5",
    name: "Mechanical Keyboard RGB",
    description: "Professional gaming keyboard with customizable RGB lighting",
    price: 189.99,
    discount_percent: 25,
    image_url: "/images/product/ridzwan.jpg",
    stock: 56,
    is_new: true,
    is_popular: false,
  },
  {
    id: "6",
    name: "Portable SSD 1TB",
    description: "Super fast external storage with USB 3.2 connectivity",
    price: 129.99,
    discount_percent: 5,
    image_url: "/images/product/budha.jpg",
    stock: 67,
    is_new: false,
    is_popular: true,
  },
]

export const MOCK_USERS = [
  {
    id: "1",
    email: "admin@deegee.com",
    password: "password",
    name: "Admin User",
    role: "admin",
  },
  {
    id: "2",
    email: "user1@deegee.com",
    password: "password",
    name: "John Doe",
    role: "user",
  },
  {
    id: "3",
    email: "user2@deegee.com",
    password: "password",
    name: "Jane Smith",
    role: "user",
  },
  {
    id: "4",
    email: "user3@deegee.com",
    password: "password",
    name: "Mike Johnson",
    role: "user",
  },
  {
    id: "5",
    email: "user4@deegee.com",
    password: "password",
    name: "Sarah Williams",
    role: "user",
  },
  {
    id: "6",
    email: "user5@deegee.com",
    password: "password",
    name: "Tom Brown",
    role: "user",
  },
  {
    id: "7",
    email: "user6@deegee.com",
    password: "password",
    name: "Emily Davis",
    role: "user",
  },
  {
    id: "8",
    email: "user7@deegee.com",
    password: "password",
    name: "David Miller",
    role: "user",
  },
  {
    id: "9",
    email: "user8@deegee.com",
    password: "password",
    name: "Lisa Anderson",
    role: "user",
  },
  {
    id: "10",
    email: "user9@deegee.com",
    password: "password",
    name: "Chris Taylor",
    role: "user",
  },
  {
    id: "11",
    email: "user10@deegee.com",
    password: "password",
    name: "Rachel Thomas",
    role: "user",
  },
]
