export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life",
    price: 299.99,
    discount_percent: 15,
    image_url: "/premium-wireless-headphones.png",
    stock: 45,
    is_new: true,
    is_popular: false,
  },
  {
    id: "2",
    name: "Ultra 4K Webcam",
    description: "Crystal clear 4K video quality with auto-focus and built-in microphone",
    price: 149.99,
    discount_percent: 0,
    image_url: "/4k-webcam.png",
    stock: 32,
    is_new: false,
    is_popular: true,
  },
  {
    id: "3",
    name: "Smart Watch Pro",
    description: "Advanced fitness tracking, heart rate monitor, and 14-day battery life",
    price: 399.99,
    discount_percent: 20,
    image_url: "/smart-watch-pro.jpg",
    stock: 28,
    is_new: true,
    is_popular: true,
  },
  {
    id: "4",
    name: "USB-C Hub Adapter",
    description: "All-in-one hub with multiple ports for seamless connectivity",
    price: 79.99,
    discount_percent: 10,
    image_url: "/usb-c-hub-adapter.jpg",
    stock: 120,
    is_new: false,
    is_popular: false,
  },
  {
    id: "5",
    name: "Mechanical Keyboard RGB",
    description: "Professional gaming keyboard with customizable RGB lighting",
    price: 189.99,
    discount_percent: 25,
    image_url: "/mechanical-keyboard-rgb.jpg",
    stock: 56,
    is_new: true,
    is_popular: false,
  },
  {
    id: "6",
    name: "Portable SSD 1TB",
    description: "Super fast external storage with USB 3.2 connectivity",
    price: 129.99,
    discount_percent: 5,
    image_url: "/portable-ssd-1tb.jpg",
    stock: 67,
    is_new: false,
    is_popular: true,
  },
  {
    id: "7",
    name: "Ergonomic Mouse Wireless",
    description: "Comfortable wireless mouse with adjustable DPI and long battery life",
    price: 59.99,
    discount_percent: 0,
    image_url: "/ergonomic-wireless-mouse.jpg",
    stock: 89,
    is_new: true,
    is_popular: false,
  },
  {
    id: "8",
    name: "Laptop Stand Adjustable",
    description: "Premium aluminum laptop stand with multiple height positions",
    price: 99.99,
    discount_percent: 12,
    image_url: "/laptop-stand-adjustable.jpg",
    stock: 45,
    is_new: false,
    is_popular: true,
  },
  {
    id: "9",
    name: "LED Desk Lamp",
    description: "Dimmable LED lamp with three color modes and USB charging",
    price: 49.99,
    discount_percent: 8,
    image_url: "/led-desk-lamp.png",
    stock: 102,
    is_new: true,
    is_popular: false,
  },
  {
    id: "10",
    name: "Monitor 27 Inch 4K",
    description: "Ultra-high definition 27-inch monitor with HDR support",
    price: 599.99,
    discount_percent: 30,
    image_url: "/monitor-27-4k-uhd.jpg",
    stock: 18,
    is_new: false,
    is_popular: true,
  },
  {
    id: "11",
    name: "Wireless Charging Pad",
    description: "Fast charging pad compatible with all Qi-enabled devices",
    price: 39.99,
    discount_percent: 15,
    image_url: "/wireless-charging-pad.png",
    stock: 78,
    is_new: true,
    is_popular: false,
  },
  {
    id: "12",
    name: "Bluetooth Speaker Premium",
    description: "Portable waterproof speaker with 360-degree sound",
    price: 149.99,
    discount_percent: 20,
    image_url: "/bluetooth-speaker-premium.jpg",
    stock: 51,
    is_new: false,
    is_popular: true,
  },
]

export const MOCK_USERS = [
  {
    id: "1",
    email: "admin@deegee.com",
    password: "password",
    name: "Admin User",
    role: "admin",
  },
  {
    id: "2",
    email: "user1@deegee.com",
    password: "password",
    name: "John Doe",
    role: "user",
  },
  {
    id: "3",
    email: "user2@deegee.com",
    password: "password",
    name: "Jane Smith",
    role: "user",
  },
  {
    id: "4",
    email: "user3@deegee.com",
    password: "password",
    name: "Mike Johnson",
    role: "user",
  },
  {
    id: "5",
    email: "user4@deegee.com",
    password: "password",
    name: "Sarah Williams",
    role: "user",
  },
  {
    id: "6",
    email: "user5@deegee.com",
    password: "password",
    name: "Tom Brown",
    role: "user",
  },
  {
    id: "7",
    email: "user6@deegee.com",
    password: "password",
    name: "Emily Davis",
    role: "user",
  },
  {
    id: "8",
    email: "user7@deegee.com",
    password: "password",
    name: "David Miller",
    role: "user",
  },
  {
    id: "9",
    email: "user8@deegee.com",
    password: "password",
    name: "Lisa Anderson",
    role: "user",
  },
  {
    id: "10",
    email: "user9@deegee.com",
    password: "password",
    name: "Chris Taylor",
    role: "user",
  },
  {
    id: "11",
    email: "user10@deegee.com",
    password: "password",
    name: "Rachel Thomas",
    role: "user",
  },
]
